# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 20:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinesePiece',
            fields=[
                ('pieceId', models.AutoField(primary_key=True, serialize=False)),
                ('catalogue', models.CharField(blank=True, max_length=200, null=True, verbose_name='Catalogue')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('composer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Composer')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contactId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('homePhone', models.IntegerField(blank=True, null=True, verbose_name='Home Phone')),
                ('mobilePhone', models.IntegerField(blank=True, null=True, verbose_name='Mobile Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=200, null=True, verbose_name='State')),
                ('zipCode', models.IntegerField(blank=True, null=True, verbose_name='Zip Code')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(blank=True, max_length=200, null=True, verbose_name='First Name')),
                ('middleName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Middle Name')),
                ('lastName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('pieceId', models.AutoField(primary_key=True, serialize=False)),
                ('catalogue', models.CharField(blank=True, max_length=200, null=True, verbose_name='Catalogue')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('composer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Composer')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='registration_site.Location')),
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='registration_site.Contact')),
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration_site.Person')),
            ],
            bases=('registration_site.person', 'registration_site.contact', 'registration_site.location'),
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration_site.Person')),
                ('instrument', models.CharField(blank=True, max_length=200, null=True, verbose_name='instrument')),
                ('accompanist', models.CharField(blank=True, max_length=200, null=True, verbose_name='Accompanist')),
                ('group', models.CharField(blank=True, max_length=200, null=True, verbose_name='Group')),
            ],
            bases=('registration_site.person',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='registration_site.Location')),
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='registration_site.Contact')),
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration_site.Person')),
            ],
            bases=('registration_site.person', 'registration_site.contact', 'registration_site.location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='registration_site.Parent', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='performer',
            name='_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='registration_site.Teacher', verbose_name="Teacher's Information"),
        ),
        migrations.AddField(
            model_name='performer',
            name='chinesePiece',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chinesePiece', to='registration_site.ChinesePiece', verbose_name='Chinese Piece'),
        ),
        migrations.AddField(
            model_name='performer',
            name='owningProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwner', to='registration_site.Profile', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='performer',
            name='piece1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piece1', to='registration_site.Piece', verbose_name='First Piece'),
        ),
        migrations.AddField(
            model_name='performer',
            name='piece2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piece2', to='registration_site.Piece', verbose_name='Second Piece'),
        ),
    ]
