# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contactId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('homePhone', models.IntegerField(verbose_name='Home Phone')),
                ('mobilePhone', models.IntegerField(verbose_name='Mobile Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContestInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruments', models.CharField(max_length=200, verbose_name='Group')),
                ('accompanist', models.CharField(max_length=200, verbose_name='Accompanist')),
                ('group', models.CharField(max_length=200, verbose_name='Group')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('state', models.CharField(max_length=200, verbose_name='State')),
                ('zipCode', models.IntegerField(verbose_name='Zip Code')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=200, verbose_name='First Name')),
                ('middleName', models.CharField(max_length=200, verbose_name='Middle Name')),
                ('lastName', models.CharField(max_length=200, verbose_name='Last Name')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('pieceId', models.AutoField(primary_key=True, serialize=False)),
                ('isChinese', models.BooleanField(verbose_name='Chinese Piece')),
                ('catalogue', models.CharField(max_length=200, verbose_name='Catalogue')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('composer', models.CharField(max_length=200, verbose_name='Composer')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='registration_site.Location')),
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='registration_site.Contact')),
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration_site.Person')),
            ],
            bases=('registration_site.person', 'registration_site.contact', 'registration_site.location'),
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='registration_site.Location')),
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration_site.Person')),
            ],
            bases=('registration_site.person', 'registration_site.location'),
        ),
        migrations.CreateModel(
            name='TeacherInformation',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='registration_site.Location')),
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='registration_site.Contact')),
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration_site.Person')),
            ],
            bases=('registration_site.person', 'registration_site.contact', 'registration_site.location'),
        ),
        migrations.AddField(
            model_name='contestinformation',
            name='chinesePiece',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chinesePiece', to='registration_site.Piece', verbose_name='Chinese Piece'),
        ),
        migrations.AddField(
            model_name='contestinformation',
            name='piece1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='piece1', to='registration_site.Piece', verbose_name='First Piece'),
        ),
        migrations.AddField(
            model_name='contestinformation',
            name='piece2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piece2', to='registration_site.Piece', verbose_name='Second Piece'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='contestInformation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contestInformation', to='registration_site.ContestInformation', verbose_name='Contest Information'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='registration_site.Parent', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='performer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performer', to='registration_site.Performer', verbose_name='Performer'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='teacherInformation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacherInformation', to='registration_site.TeacherInformation', verbose_name="Teacher's Information"),
        ),
    ]
