# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0002_remove_location_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performer',
            name='location_ptr',
        ),
    ]
