# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0003_remove_performer_location_ptr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performer',
            name='instruments',
        ),
        migrations.AddField(
            model_name='performer',
            name='instrument',
            field=models.CharField(default='', max_length=200, verbose_name='instrument'),
            preserve_default=False,
        ),
    ]
