# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 01:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration_site', '0004_auto_20161029_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='performers',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='contact_ptr',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='location_ptr',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='contact_ptr',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='location_ptr',
        ),
        migrations.AddField(
            model_name='parent',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_contact', to='registration_site.Contact', verbose_name="Parent's Contact"),
        ),
        migrations.AddField(
            model_name='parent',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_location', to='registration_site.Location', verbose_name="Parent's Location"),
        ),
        migrations.AddField(
            model_name='parent',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_person', to='registration_site.Contact', verbose_name="Parent's Info"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_contact', to='registration_site.Contact', verbose_name="Teacher's Contact"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_location', to='registration_site.Location', verbose_name="Teachers's Location"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_person', to='registration_site.Contact', verbose_name="Teacher's Info"),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='homePhone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Home Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobilePhone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mobile Phone'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='location',
            name='zipCode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='accompanist',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Accompanist'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='chinesePiece',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chinesePiece', to='registration_site.Piece', verbose_name='Chinese Piece'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='group',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='instrument',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='piece1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piece1', to='registration_site.Piece', verbose_name='First Piece'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='piece2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piece2', to='registration_site.Piece', verbose_name='Second Piece'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='teachers',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='registration_site.Teacher', verbose_name="Teacher's Information"),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstName',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastName',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middleName',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='catalogue',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Catalogue'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='composer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Composer'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.DeleteModel(
            name='Contestant',
        ),
        migrations.AddField(
            model_name='profile',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='registration_site.Parent', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='profile',
            name='performers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performer', to='registration_site.Performer', verbose_name='Performer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
