# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 09:19
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards_applying_for', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('C', 'Chinese Award'), ('J', 'J&V Foundation Award'), ('B', 'Bach Award'), ('Y', 'Young Artist Award')], max_length=1, verbose_name='Awards Applying For'), size=None)),
                ('instrument_category', models.CharField(choices=[('PI', 'Piano'), ('VN', 'Violin'), ('VA', 'Viola'), ('CE', 'Cello'), ('CN', 'Chinese Traditional Instruments'), ('MA', 'Marimba'), ('FL', 'Flute'), ('CL', 'Clarinet'), ('VO', 'Vocal'), ('CNE', 'Chinese Traditional Instruments Ensemble'), ('CHE', 'Chamber Ensemble'), ('VOE', 'Vocal Ensemble')], max_length=4)),
                ('age_category', models.IntegerField(choices=[(8, 'Age 8 or under'), (9, 'Age 9 or under'), (10, 'Age 10 or under'), (11, 'Age 11 or under'), (12, 'Age 12 or under'), (13, 'Age 13 or under'), (14, 'Age 14 or under'), (15, 'Age 15 or under'), (17, 'Age 17 or under'), (22, 'Age 22 or under'), (30, 'Age 30 or under')])),
                ('submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'default_related_name': 'entry',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200, verbose_name='First Name')),
                ('middleName', models.CharField(max_length=200, verbose_name='Middle Name')),
                ('lastName', models.CharField(max_length=200, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.IntegerField(verbose_name='Phone Number')),
                ('instrument', models.CharField(max_length=200)),
                ('teacher_first_name', models.CharField(max_length=200, verbose_name="Teacher's First Name")),
                ('teacher_middle_name', models.CharField(blank=True, max_length=200, verbose_name="Teacher's Middle Name")),
                ('teacher_last_name', models.CharField(max_length=200, verbose_name="Teacher's Last Name")),
                ('teacher_code', models.CharField(blank=True, max_length=200, verbose_name="Teacher's CMTANC Code")),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='registration_site.Entry', verbose_name='USIMC User')),
            ],
            options={
                'default_related_name': 'person',
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogue', models.CharField(blank=True, max_length=200, verbose_name='Catalogue')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('composer', models.CharField(max_length=200, verbose_name='Composer')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piece', to='registration_site.Entry', verbose_name='Piece')),
            ],
            options={
                'default_related_name': 'piece',
            },
        ),
        migrations.CreateModel(
            name='USIMCUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='usimc_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='registration_site.USIMCUser', verbose_name='USIMC User'),
        ),
    ]
