# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='middleName',
            new_name='middle_name',
        ),
    ]
