# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0002_auto_20170226_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=200, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='instrument',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.IntegerField(null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='teacher_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Teacher's CMTANC Code (Optional)"),
        ),
        migrations.AlterField(
            model_name='person',
            name='teacher_first_name',
            field=models.CharField(max_length=200, null=True, verbose_name="Teacher's First Name"),
        ),
        migrations.AlterField(
            model_name='person',
            name='teacher_last_name',
            field=models.CharField(max_length=200, null=True, verbose_name="Teacher's Last Name"),
        ),
        migrations.AlterField(
            model_name='person',
            name='teacher_middle_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Teacher's Middle Name"),
        ),
    ]
