# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0003_auto_20170226_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='teacher_code',
            field=models.CharField(max_length=200, null=True, verbose_name="Teacher's CMTANC Code (Optional)"),
        ),
        migrations.AlterField(
            model_name='person',
            name='teacher_middle_name',
            field=models.CharField(max_length=200, null=True, verbose_name="Teacher's Middle Name"),
        ),
    ]
