# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import registration_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0006_person_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=registration_site.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='piece',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='piece',
            name='updated_at',
            field=registration_site.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usimcuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usimcuser',
            name='updated_at',
            field=registration_site.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entry',
            name='updated_at',
            field=registration_site.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
