# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0007_auto_20170228_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='is_chinese',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='teacher_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Teacher's CMTANC Code"),
        ),
    ]
