# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-08 08:36
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import registration_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0007_auto_20170228_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnsembleMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.IntegerField(blank=True, null=True, verbose_name='Phone Number')),
                ('instrument', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', registration_site.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'default_related_name': 'ensemble_members',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.IntegerField(blank=True, null=True, verbose_name='Phone Number')),
                ('cmtanc_code', models.CharField(blank=True, max_length=200, null=True, verbose_name="Teacher's CMTANC Membership ID")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', registration_site.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='person',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='teacher_code',
        ),
        migrations.RemoveField(
            model_name='person',
            name='teacher_first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='teacher_last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='teacher_middle_name',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='catalogue',
        ),
        migrations.AddField(
            model_name='entry',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='entry',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='entry',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='entry',
            name='lead_performer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='registration_site.Person', verbose_name='Lead Performer'),
        ),
        migrations.AddField(
            model_name='entry',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='zip_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='is_chinese',
            field=models.BooleanField(default=False, verbose_name='is Chinese Piece'),
        ),
        migrations.AddField(
            model_name='piece',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='piece',
            name='movement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Movement'),
        ),
        migrations.AddField(
            model_name='piece',
            name='opus',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Opus'),
        ),
        migrations.AddField(
            model_name='usimcuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='awards_applying_for',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Y', 'Young Artist Award'), ('C', 'Chinese Award'), ('B', 'Bach Award'), ('J', 'J.V. Award')], max_length=1, verbose_name='Awards Applying For'), size=None),
        ),
        migrations.AlterField(
            model_name='entry',
            name='instrument_category',
            field=models.CharField(choices=[('PI', 'Piano'), ('VN', 'Violin'), ('VA', 'Viola'), ('CE', 'Cello'), ('MA', 'Marimba'), ('FL', 'Flute'), ('CL', 'Clarinet'), ('VO', 'Vocal'), ('CN', 'Chinese Traditional Instruments'), ('CHE', 'Chamber Ensemble'), ('VOE', 'Vocal Ensemble'), ('CNE', 'Chinese Traditional Instruments Ensemble')], max_length=4),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='composer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Composer'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='registration_site.Entry', verbose_name='Piece'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='usimcuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usimc_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='ensemblemember',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ensemble_members', to='registration_site.Entry', verbose_name='Ensemble Member'),
        ),
        migrations.AddField(
            model_name='entry',
            name='teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='registration_site.Teacher', verbose_name='Teacher'),
        ),
    ]
