# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0008_auto_20170228_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='is_chinese',
            field=models.BooleanField(default=False, verbose_name='is Chinese Piece'),
        ),
    ]
