# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0009_auto_20170309_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='age_category',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1),
        ),
    ]
