# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import registration_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0010_auto_20170309_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email Address')),
                ('phone_number', models.IntegerField(blank=True, null=True, verbose_name='Phone Number')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', registration_site.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'default_related_name': 'parent_contact',
            },
        ),
        migrations.RemoveField(
            model_name='entry',
            name='email',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='entry',
            name='parent_contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='registration_site.ParentContact', verbose_name='Parent Contact'),
        ),
    ]
