# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-04 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0010_auto_20170304_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='catalogue',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Catalogue'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='composer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Composer'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
    ]
