# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0011_auto_20170309_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensemblemember',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
