# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0013_auto_20170312_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='instrument_category',
            field=models.CharField(choices=[(b'viola', b'Viola'), (b'marimba', b'Marimba'), (b'flute', b'Flute'), (b'vocal', b'Vocal'), (b'cello', b'Cello'), (b'violin', b'Violin'), (b'piano', b'Piano'), (b'chinese_traditional_instruments', b'Chinese Traditional Instruments'), (b'clarinet', b'Clarinet'), (b'vocal_ensemble', b'Vocal Ensemble'), (b'chamber_ensemble', b'Chamber Ensemble'), (b'chinese_traditional_instruments_ensemble', b'Chinese Traditional Instruments Ensemble')], max_length=100),
        ),
    ]
