# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0014_auto_20170312_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensemblemember',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
