# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0015_auto_20170312_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
    ]
