# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0016_entry_is_international'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='is_international',
            new_name='is_not_international',
        ),
    ]
