# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 02:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0017_auto_20170312_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='awards_applying_for',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(b'bach_award', b'bach_award'), (b'young_artist_award', b'young_artist_award'), (b'jv_award', b'jv_award'), (b'chinese_award', b'chinese_award')], max_length=1, verbose_name='Awards Applying For'), size=None),
        ),
    ]
