# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 02:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0018_auto_20170313_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='awards_applying_for',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(b'bach_award', 'Bach Award'), (b'young_artist_award', 'Young Artist Award'), (b'jv_award', 'J.V. Award'), (b'chinese_award', 'Chinese Award')], max_length=20, verbose_name='Awards Applying For'), size=None),
        ),
    ]
