# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-16 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0021_auto_20170316_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcontact',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
    ]
