# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-16 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0022_auto_20170316_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcontact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone Number'),
        ),
    ]
