# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0024_auto_20170326_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=200)),
                ('charge_amount', models.IntegerField()),
                ('charge_customer', models.CharField(max_length=200)),
                ('charge_description', models.CharField(max_length=500)),
                ('charge_failure_message', models.CharField(max_length=500)),
                ('charge_paid', models.BooleanField()),
                ('charge_receipt_email', models.CharField(max_length=500)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charge', to='registration_site.Entry', verbose_name='Entry')),
                ('usimc_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charge', to='registration_site.USIMCUser', verbose_name='USIMC User')),
            ],
        ),
    ]
