# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0025_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='usimc_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='registration_site.USIMCUser', verbose_name='USIMC User'),
        ),
    ]
