# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0026_auto_20170326_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge', to='registration_site.Entry', verbose_name='Entry'),
        ),
    ]
