# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0027_auto_20170326_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensemblemember',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
