# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 09:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0028_auto_20170326_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Youtube Link (Only needed for Young Artist Award Entry)'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='awards_applying_for',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(b'young_artist_award', 'Young Artist Award'), (b'special_theme_bach', 'Special Theme Award - Johann Sebastian Bach'), (b'chinese_music_award', 'Chinese Music Award')], max_length=20, verbose_name='Awards Applying For'), size=None),
        ),
        migrations.AlterField(
            model_name='entry',
            name='instrument_category',
            field=models.CharField(choices=[(b'cello', b'Cello'), (b'chamber_ensemble', b'Chamber Ensemble'), (b'chinese_traditional_instrument_bowed_strings', b'Bowed Strings - Chinese Traditional Instrument'), (b'chinese_traditional_instrument_guqin', b'Guqin - Chinese Traditional Instrument'), (b'chinese_traditional_instrument_plucked_string', b'Plucked String - Chinese Traditional Instrument'), (b'chinese_traditional_instrument_professional_zither', b'Professional Zither - Chinese Traditional Instrument'), (b'chinese_traditional_instrument_woodwinds', b'Woodwinds - Chinese Traditional Instrument'), (b'chinese_traditional_instrument_zither', b'Zither - Chinese Traditional Instrument'), (b'chinese_traditional_instruments_ensemble', b'Chinese Traditional Instruments Ensemble'), (b'clarinet', b'Clarinet'), (b'flute', b'Flute'), (b'marimba', b'Marimba'), (b'piano', b'Piano'), (b'viola', b'Viola'), (b'violin', b'Violin'), (b'vocal', b'Vocal'), (b'vocal_ensemble', b'Vocal Ensemble')], max_length=100),
        ),
    ]
