# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-29 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0029_auto_20170328_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='proof_of_age',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_not_international',
            field=models.BooleanField(default=True),
        ),
    ]
