# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-31 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0032_auto_20170331_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcontact',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Email'),
        ),
    ]
