# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-31 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0035_auto_20170331_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensemblemember',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birthday',
        ),
        migrations.AddField(
            model_name='ensemblemember',
            name='day',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='ensemblemember',
            name='month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='ensemblemember',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='day',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
