# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-13 04:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0039_entry_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='zip_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='awards_applying_for',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('young_artist_award', 'Young Artist Award'), ('special_theme_bach', 'Special Theme Award - Johann Sebastian Bach'), ('chinese_music_award', 'Chinese Music Award')], max_length=20, verbose_name='Awards Applying For'), size=None),
        ),
        migrations.AlterField(
            model_name='entry',
            name='instrument_category',
            field=models.CharField(choices=[('cello', 'Cello'), ('celtic_harp', 'Celtic Harp'), ('chamber_ensemble', 'Chamber Ensemble'), ('chinese_traditional_instrument_bowed_strings', 'Bowed Strings - Chinese Traditional Instrument'), ('chinese_traditional_instrument_guqin', 'Guqin - Chinese Traditional Instrument'), ('chinese_traditional_instrument_plucked_string', 'Plucked String - Chinese Traditional Instrument'), ('chinese_traditional_instrument_professional_zither', 'Professional Guzheng (Zither) - Chinese Traditional Instrument'), ('chinese_traditional_instrument_woodwinds', 'Woodwinds - Chinese Traditional Instrument'), ('chinese_traditional_instrument_zither', 'Guzheng (Zither) - Chinese Traditional Instrument'), ('chinese_traditional_instruments_ensemble', 'Chinese Traditional Instruments Ensemble'), ('classical_guitar', 'Classical Guitar'), ('harp', 'Harp'), ('piano', 'Piano'), ('viola', 'Viola'), ('violin', 'Violin'), ('vocal', 'Vocal'), ('vocal_ensemble', 'Vocal Ensemble')], max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='proof_of_age',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
