# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-14 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_site', '0040_auto_20180212_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='instrument_category',
            field=models.CharField(choices=[('cello', 'Cello'), ('celtic_harp', 'Celtic Harp'), ('chamber_ensemble_and_piano_duet', 'Chamber Ensemble and Piano Duet'), ('chinese_traditional_instrument_bowed_strings', 'Bowed Strings - Chinese Traditional Instrument'), ('chinese_traditional_instrument_guqin', 'Guqin - Chinese Traditional Instrument'), ('chinese_traditional_instrument_plucked_string', 'Plucked String - Chinese Traditional Instrument'), ('chinese_traditional_instrument_professional_zither', 'Professional Guzheng (Zither) - Chinese Traditional Instrument'), ('chinese_traditional_instrument_woodwinds', 'Woodwinds - Chinese Traditional Instrument'), ('chinese_traditional_instrument_zither', 'Guzheng (Zither) - Chinese Traditional Instrument'), ('chinese_traditional_instruments_ensemble', 'Chinese Traditional Instruments Ensemble'), ('classical_guitar', 'Classical Guitar'), ('harp', 'Harp'), ('piano', 'Piano'), ('viola', 'Viola'), ('violin', 'Violin'), ('vocal', 'Vocal'), ('vocal_ensemble', 'Vocal Ensemble')], max_length=100),
        ),
    ]
